# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that. If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.

# Site settings
title:            NYC Islandora Working Group
email:            example@example.com
description:      Github Pages test for Islandora Working Group.
url:              ''
baseurl:          ''

twitter_username: mariinyrop
github_username:  mnyrop

# Build settings
markdown:         kramdown
remote_theme:     broccolini/athena
permalink:        pretty
exclude:          [Gemfile*, vendor, README.md, docs]
plugins:          [jekyll-feed]
github:           [metadata]
